/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InsertationSort */

#ifndef _Included_InsertationSort
#define _Included_InsertationSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InsertationSort
 * Method:    insearch
 * Signature: ([ID)[I
 */
JNIEXPORT jintArray JNICALL Java_InsertationSort_insearch
  (JNIEnv *, jobject, jintArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
